export const weaponsList = {
  gauntlet: {
    weaponName: "Gauntlet",
    cost: 20,
    dmgS: "1d2",
    dmgM: "1d3",
    critical: "x2",
    range: null,
    weight: 1,
    type: "B",
    cat: "simple",
    startingEquipment: [],
  },
  dagger: {
    weaponName: "Dagger",
    cost: 20,
    dmgS: "1d3",
    dmgM: "1d4",
    critical: "19-20/x2",
    range: 10,
    weight: 1,
    type: "P or S",
    cat: "simple",
    startingEquipment: ["Barbarian", "Rogue"],
  },

  daggerPunching: {
    weaponName: "Dagger, punching",
    cost: 20,
    dmgS: "1d3",
    dmgM: "1d4",
    critical: "x3",
    range: null,
    weight: 1,
    type: "P",
    cat: "simple",
    startingEquipment: [],
  },

  gauntletSpiked: {
    weaponName: "Gauntlet, spiked",
    cost: 50,
    dmgS: "1d3",
    dmgM: "1d4",
    critical: "x2",
    range: null,
    weight: 1,
    type: "P",
    cat: "simple",
    startingEquipment: [],
  },

  maceLight: {
    weaponName: "Mace, light",
    cost: 50,
    dmgS: "1d4",
    dmgM: "1d6",
    critical: "x2",
    range: null,
    weight: 4,
    type: "B",
    cat: "simple",
    startingEquipment: [],
  },

  sickle: {
    weaponName: "Sickle",
    cost: 60,
    dmgS: "1d4",
    dmgM: "1d6",
    critical: "x2",
    range: null,
    weight: 2,
    type: "S",
    cat: "simple",
    startingEquipment: [],
  },

  club: {
    weaponName: "Club",
    cost: 0,
    dmgS: "1d4",
    dmgM: "1d6",
    critical: "x2",
    range: 10,
    weight: 3,
    type: "B",
    cat: "simple",
    startingEquipment: ["Druid"],
  },

  maceHeavy: {
    weaponName: "Mace, heavy",
    cost: 120,
    dmgS: "1d6",
    dmgM: "1d8",
    critical: "x2",
    range: null,
    weight: 8,
    type: "B",
    cat: "simple",
    startingEquipment: ["Cleric"],
  },

  morningstar: {
    weaponName: "Morningstar",
    cost: 80,
    dmgS: "1d6",
    dmgM: "1d8",
    critical: "x2",
    range: null,
    weight: 6,
    type: "B and P",
    cat: "simple",
    startingEquipment: [],
  },

  shortspear: {
    weaponName: "Shortspear",
    cost: 10,
    dmgS: "1d4",
    dmgM: "1d6",
    critical: "x2",
    range: 20,
    weight: 3,
    type: "P",
    cat: "simple",
    startingEquipment: ["Sorcerer"],
  },

  longspear: {
    weaponName: "Longspear",
    cost: 50,
    dmgS: "1d6",
    dmgM: "1d8",
    critical: "x3",
    range: null,
    weight: 9,
    type: "P",
    cat: "simple",
    startingEquipment: [],
  },

  quarterstaff: {
    weaponName: "Quarterstaff",
    cost: 0,
    dmgS: "1d4/1d4",
    dmgM: "1d6/1d6",
    critical: "x2",
    range: null,
    weight: 4,
    type: "B",
    cat: "simple",
    startingEquipment: ["Monk", "Wizard"],
  },

  spear: {
    weaponName: "Spear",
    cost: 20,
    dmgS: "1d6",
    dmgM: "1d8",
    critical: "x3",
    range: 20,
    weight: 6,
    type: "P",
    cat: "simple",
    startingEquipment: [],
  },

  crossbowHeavy: {
    weaponName: "Crossbow, heavy",
    cost: 500,
    dmgS: "1d8",
    dmgM: "1d10",
    critical: "19-20/x2",
    range: 120,
    weight: 8,
    type: "P",
    cat: "simple",
    startingEquipment: [],
  },

  crossbowLight: {
    weaponName: "Crossbow, light",
    cost: 350,
    dmgS: "1d6",
    dmgM: "1d8",
    critical: "19-20/x2",
    range: 80,
    weight: 4,
    type: "P",
    cat: "simple",
    startingEquipment: ["Bard", "Cleric", "Sorcerer", "Wizard"],
  },

  dart: {
    weaponName: "Dart",
    cost: 50,
    dmgS: "1d3",
    dmgM: "1d4",
    critical: "x2",
    range: 20,
    weight: 0.5,
    type: "P",
    cat: "simple",
    startingEquipment: [],
  },

  javelin: {
    weaponName: "Javelin",
    cost: 10,
    dmgS: "1d4",
    dmgM: "1d6",
    critical: "x2",
    range: 30,
    weight: 2,
    type: "p",
    cat: "simple",
    startingEquipment: [],
  },

  sling: {
    weaponName: "Sling",
    cost: 0,
    dmgS: "1d3",
    dmgM: "1d4",
    critical: "x2",
    range: 50,
    weight: 0,
    type: "B",
    cat: "simple",
    startingEquipment: ["Monk"],
  },

  axeThrowing: {
    weaponName: "Axe, throwing",
    cost: 80,
    dmgS: "1d4",
    dmgM: "1d6",
    critical: "x2",
    range: 10,
    weight: 2,
    type: "S",
    cat: "martial",
    startingEquipment: [],
  },

  hammerLight: {
    weaponName: "Hammer, light",
    cost: 10,
    dmgS: "1d3",
    dmgM: "1d4",
    critical: "x2",
    range: 20,
    weight: 2,
    type: "B",
    cat: "martial",
    startingEquipment: [],
  },

  handAxe: {
    weaponName: "Handaxe",
    cost: 60,
    dmgS: "1d4",
    dmgM: "1d6",
    critical: "x3",
    range: null,
    weight: 3,
    type: "S",
    cat: "martial",
    startingEquipment: [],
  },

  kukri: {
    weaponName: "Kukri",
    cost: 80,
    dmgS: "1d3",
    dmgM: "1d4",
    critical: "18-20/x2",
    range: null,
    weight: 2,
    type: "S",
    cat: "martial",
    startingEquipment: [],
  },

  pickLight: {
    weaponName: "Pick, light",
    cost: 40,
    dmgS: "1d3",
    dmgM: "1d4",
    critical: "x4",
    range: null,
    weight: 3,
    type: "P",
    cat: "martial",
    startingEquipment: [],
  },

  sap: {
    weaponName: "Sap",
    cost: 10,
    dmgS: "1d4",
    dmgM: "1d6",
    critical: "x2",
    range: null,
    weight: 2,
    type: "B",
    cat: "martial",
    startingEquipment: [],
  },

  shieldLight: {
    weaponName: "Shield, light",
    cost: null,
    dmgS: "1d2",
    dmgM: "1d3",
    critical: "x2",
    range: null,
    weight: null,
    type: "B",
    cat: "martial",
    startingEquipment: [],
  },

  spikedArmor: {
    weaponName: "Spiked Armor",
    cost: null,
    dmgS: "1d4",
    dmgM: "1d6",
    critical: "x2",
    range: null,
    weight: null,
    type: "P",
    cat: "martial",
    startingEquipment: [],
  },

  spikedShieldLight: {
    weaponName: "Spiked shield, light",
    cost: null,
    dmgS: "1d3",
    dmgM: "1d4",
    critical: "x2",
    range: null,
    weight: null,
    type: "B",
    cat: "martial",
    startingEquipment: [],
  },

  swordShort: {
    weaponName: "Sword, short",
    cost: 100,
    dmgS: "1d4",
    dmgM: "1d6",
    critical: "19-20/x2",
    range: null,
    weight: 2,
    type: "P",
    cat: "martial",
    startingEquipment: ["Ranger", "Rogue"],
  },

  battleAxe: {
    weaponName: "Battleaxe",
    cost: 100,
    dmgS: "1d6",
    dmgM: "1d8",
    critical: "x3",
    range: null,
    weight: 6,
    type: "S",
    cat: "martial",
    startingEquipment: [],
  },

  flail: {
    weaponName: "Flail",
    cost: 80,
    dmgS: "1d6",
    dmgM: "1d8",
    critical: "x2",
    range: null,
    weight: 5,
    type: "B",
    cat: "martial",
    startingEquipment: [],
  },

  longsword: {
    weaponName: "Longsword",
    cost: 150,
    dmgS: "1d6",
    dmgM: "1d8",
    critical: "19-20/x2",
    range: null,
    weight: 4,
    type: "S",
    cat: "martial",
    startingEquipment: ["Bard", "Paladin", "Ranger"],
  },

  pickHeavy: {
    weaponName: "Pick, heavy",
    cost: 80,
    dmgS: "1d4",
    dmgM: "1d6",
    critical: "x4",
    range: null,
    weight: 6,
    type: "P",
    cat: "martial",
    startingEquipment: [],
  },

  rapier: {
    weaponName: "Rapier",
    cost: 200,
    dmgS: "1d4",
    dmgM: "1d6",
    critical: "18-20/x2",
    range: null,
    weight: 2,
    type: "P",
    cat: "martial",
    startingEquipment: [],
  },

  scimitar: {
    weaponName: "Scimitar",
    cost: 150,
    dmgS: "1d4",
    dmgM: "1d6",
    critical: "18-20/x2",
    range: null,
    weight: 4,
    type: "S",
    cat: "martial",
    startingEquipment: ["Druid"],
  },

  shieldHeavy: {
    weaponName: "Shield, heavy",
    cost: null,
    dmgS: "1d3",
    dmgM: "1d4",
    critical: "x2",
    range: null,
    weight: null,
    type: "B",
    cat: "martial",
    startingEquipment: [],
  },

  spikedShieldHeavy: {
    weaponName: "Spiked shield, heavy",
    cost: null,
    dmgS: "1d4",
    dmgM: "1d6",
    critical: "x2",
    range: null,
    weight: null,
    type: "P",
    cat: "martial",
    startingEquipment: [],
  },

  trident: {
    weaponName: "Trident",
    cost: 150,
    dmgS: "1d6",
    dmgM: "1d8",
    critical: "x2",
    range: 10,
    weight: 4,
    type: "P",
    cat: "martial",
    startingEquipment: [],
  },

  warhammer: {
    weaponName: "Warhammer",
    cost: 120,
    dmgS: "1d6",
    dmgM: "1d8",
    critical: "x3",
    range: null,
    weight: 5,
    type: "B",
    cat: "martial",
    startingEquipment: [],
  },

  falchion: {
    weaponName: "Falchion",
    cost: 750,
    dmgS: "1d6",
    dmgM: "2d4",
    critical: "18-20/x2",
    range: null,
    weight: 8,
    type: "S",
    cat: "martial",
    startingEquipment: [],
  },

  glaive: {
    weaponName: "Glaive",
    cost: 80,
    dmgS: "1d8",
    dmgM: "1d10",
    critical: "x3",
    range: null,
    weight: 10,
    type: "S",
    cat: "martial",
    startingEquipment: [],
  },

  greataxe: {
    weaponName: "Greataxe",
    cost: 200,
    dmgS: "1d10",
    dmgM: "1d12",
    critical: "x3",
    range: null,
    weight: 12,
    type: "S",
    cat: "martial",
    startingEquipment: ["Barbarian"],
  },

  greatclub: {
    weaponName: "Greatclub",
    cost: 50,
    dmgS: "1d8",
    dmgM: "1d10",
    critical: "x2",
    range: null,
    weight: 8,
    type: "B",
    cat: "martial",
    startingEquipment: [],
  },

  flailHeavy: {
    weaponName: "Flail, heavy",
    cost: 150,
    dmgS: "1d8",
    dmgM: "1d10",
    critical: "19-20/x2",
    range: null,
    weight: 10,
    type: "B",
    cat: "martial",
    startingEquipment: [],
  },

  greatsword: {
    weaponName: "Greatsword",
    cost: 500,
    dmgS: "1d10",
    dmgM: "2d6",
    critical: "19-20/x2",
    range: null,
    weight: 8,
    type: "S",
    cat: "martial",
    startingEquipment: ["Fighter"],
  },

  guisarme: {
    weaponName: "Guisarme",
    cost: 90,
    dmgS: "1d6",
    dmgM: "2d4",
    critical: "x3",
    range: null,
    weight: 12,
    type: "S",
    cat: "martial",
    startingEquipment: [],
  },

  halberd: {
    weaponName: "Halberd",
    cost: 100,
    dmgS: "1d8",
    dmgM: "1d10",
    critical: "x3",
    range: null,
    weight: 12,
    type: "P or S",
    cat: "martial",
    startingEquipment: [],
  },

  lance: {
    weaponName: "Lance",
    cost: 100,
    dmgS: "1d6",
    dmgM: "1d8",
    critical: "x3",
    range: null,
    weight: 10,
    type: "P",
    cat: "martial",
    startingEquipment: [],
  },

  ranseur: {
    weaponName: "Ranseur",
    cost: 100,
    dmgS: "1d6",
    dmgM: "2d4",
    critical: "x3",
    range: null,
    weight: 12,
    type: "P",
    cat: "martial",
    startingEquipment: [],
  },

  scythe: {
    weaponName: "Scythe",
    cost: 180,
    dmgS: "1d6",
    dmgM: "2d4",
    critical: "x4",
    range: null,
    weight: 10,
    type: "P or S",
    cat: "martial",
    startingEquipment: [],
  },

  longbow: {
    weaponName: "Longbow",
    cost: 750,
    dmgS: "1d6",
    dmgM: "1d8",
    critical: "x3",
    range: 100,
    weight: 3,
    type: "P",
    cat: "martial",
    startingEquipment: [],
  },

  longbowComposite: {
    weaponName: "Longbow, composite",
    cost: 1000,
    dmgS: "1d6",
    dmgM: "1d8",
    critical: "x3",
    range: 110,
    weight: 3,
    type: "P",
    cat: "martial",
    startingEquipment: [],
  },

  shortbow: {
    weaponName: "Shortbow",
    cost: 30,
    dmgS: "1d4",
    dmgM: "1d6",
    critical: "x3",
    range: 60,
    weight: 2,
    type: "P",
    cat: "martial",
    startingEquipment: ["Barbarian", "Fighter", "Paladin", "Rogue"],
  },

  shortbowComposite: {
    weaponName: "Shortbow, composite",
    cost: 30,
    dmgS: "1d4",
    dmgM: "1d6",
    critical: "x3",
    range: 70,
    weight: 2,
    type: "P",
    cat: "martial",
    startingEquipment: [],
  },

  kama: {
    weaponName: "Kama",
    cost: 20,
    dmgS: "1d4",
    dmgM: "1d6",
    critical: "x2",
    range: null,
    weight: 2,
    type: "S",
    cat: "exotic",
    startingEquipment: [],
  },

  nunchaku: {
    weaponName: "Nunchaku",
    cost: 20,
    dmgS: "1d4",
    dmgM: "1d6",
    critical: "x2",
    range: null,
    weight: 2,
    type: "B",
    cat: "exotic",
    startingEquipment: [],
  },

  sai: {
    weaponName: "Sai",
    cost: 100,
    dmgS: "1d3",
    dmgM: "1d4",
    critical: "x2",
    range: 10,
    weight: 1,
    type: "B",
    cat: "exotic",
    startingEquipment: [],
  },

  siangham: {
    weaponName: "Siangham",
    cost: 30,
    dmgS: "1d4",
    dmgM: "1d6",
    critical: "x2",
    range: null,
    weight: 1,
    type: "P",
    cat: "exotic",
    startingEquipment: [],
  },

  swordBastard: {
    weaponName: "Sword, bastard",
    cost: 350,
    dmgS: "1d8",
    dmgM: "1d10",
    critical: "19-20/x2",
    range: null,
    weight: 6,
    type: "S",
    cat: "exotic",
    startingEquipment: [],
  },

  waraxeDwarven: {
    weaponName: "Waraxe, Dwarven",
    cost: 300,
    dmgS: "1d8",
    dmgM: "1d10",
    critical: "x3",
    range: null,
    weight: 8,
    type: "S",
    cat: "exotic",
    startingEquipment: [],
  },

  whip: {
    weaponName: "Whip",
    cost: 10,
    dmgS: "1d2",
    dmgM: "1d3",
    critical: "x2",
    range: null,
    weight: 2,
    type: "S",
    cat: "exotic",
    startingEquipment: [],
  },

  axeOrcDouble: {
    weaponName: "Axe, orc double",
    cost: 600,
    dmgS: "1d6/1d6",
    dmgM: "1d8/1d8",
    critical: "x3",
    range: null,
    weight: 15,
    type: "S",
    cat: "exotic",
    startingEquipment: [],
  },

  chainSpiked: {
    weaponName: "Chain, spiked",
    cost: 250,
    dmgS: "1d6",
    dmgM: "2d4",
    critical: "x2",
    range: null,
    weight: 10,
    type: "P",
    cat: "exotic",
    startingEquipment: [],
  },

  flailDire: {
    weaponName: "Flail, dire",
    cost: 90,
    dmgS: "1d6/1d6",
    dmgM: "1d8/1d8",
    critical: "x2",
    range: null,
    weight: 10,
    type: "B",
    cat: "exotic",
    startingEquipment: [],
  },

  hammerGnomeHooked: {
    weaponName: "Hammer, gnome hooked",
    cost: 200,
    dmgS: "1d6/1d4",
    dmgM: "1d8/1d6",
    critical: "x3/x4",
    range: null,
    weight: 6,
    type: "B or P",
    cat: "exotic",
    startingEquipment: [],
  },

  swordTwoBladed: {
    weaponName: "Sword, two-bladed",
    cost: 1000,
    dmgS: "1d6/1d6",
    dmgM: "1d8/1d8",
    critical: "19-20/x2",
    range: null,
    weight: 10,
    type: "S",
    cat: "exotic",
    startingEquipment: [],
  },

  urgroshDwarven: {
    weaponName: "Urgrosh, dwarven",
    cost: 500,
    dmgS: "1d6/1d4",
    dmgM: "1d8/1d6",
    critical: "x3",
    range: null,
    weight: 12,
    type: "S or P",
    cat: "exotic",
    startingEquipment: [],
  },

  bolas: {
    weaponName: "Bolas",
    cost: 50,
    dmgS: "1d3",
    dmgM: "1d4",
    critical: "x2",
    range: 10,
    weight: 2,
    type: "B",
    cat: "exotic",
    startingEquipment: [],
  },

  crossbowHand: {
    weaponName: "Crossbow, hand",
    cost: 100,
    dmgS: "1d3",
    dmgM: "1d4",
    critical: "19-20/x2",
    range: 30,
    weight: 2,
    type: "P",
    cat: "exotic",
    startingEquipment: [],
  },

  crossbowRepeatingHeavy: {
    weaponName: "Crossbow, repeating heavy",
    cost: 4000,
    dmgS: "1d8",
    dmgM: "1d10",
    critical: "19-20/x2",
    range: 120,
    weight: 12,
    type: "P",
    cat: "exotic",
    startingEquipment: [],
  },

  crossbowRepeatingLight: {
    weaponName: "Crossbow, repeating light",
    cost: 2500,
    dmgS: "1d6",
    dmgM: "1d8",
    critical: "19-20/x2",
    range: 80,
    weight: 6,
    type: "P",
    cat: "exotic",
    startingEquipment: [],
  },

  net: {
    weaponName: "Net",
    cost: 200,
    dmgS: null,
    dmgM: null,
    critical: null,
    range: 10,
    weight: 6,
    type: null,
    cat: "exotic",
    startingEquipment: [],
  },

  shuriken: {
    weaponName: "Shuriken (5)",
    cost: 10,
    dmgS: "1",
    dmgM: "1d2",
    critical: "x2",
    range: 10,
    weight: 0.5,
    type: "P",
    cat: "exotic",
    startingEquipment: [],
  },
  boltsCrossbow: {
    weaponName: "Bolts, crossbow (10)",
    cost: 10,
    dmgS: null,
    dmgM: null,
    critical: null,
    range: null,
    weight: 1,
    type: null,
    cat: "ammunition",
    startingEquipment: [],
  },

  bulletsSling: {
    weaponName: "Bullets, sling (10)",
    cost: 1,
    dmgS: null,
    dmgM: null,
    critical: null,
    range: null,
    weight: 5,
    type: null,
    cat: "ammunition",
    startingEquipment: [],
  },

  arrows: {
    weaponName: "Arrows (20)",
    cost: 10,
    dmgS: null,
    dmgM: null,
    critical: null,
    range: null,
    weight: 3,
    type: null,
    cat: "ammunition",
    startingEquipment: [],
  },
  boltsCrossbowRepeating: {
    weaponName: "Bolts, crossbow repeating (5)",
    cost: 10,
    dmgS: null,
    dmgM: null,
    critical: null,
    range: null,
    weight: 1,
    type: null,
    cat: "ammunition",
    startingEquipment: [],
  },
};
