export const featsTable = {
  acrobatic: {
    featName: "Acrobatic",
    effect: "+2 bonus on Jump and Tumble checks",
    pre: null,
    cat: "general",
    startingFeat: [],
  },
  agile: {
    featName: "Agile",
    effect: "+2 bonus on Balance and Escape Artist checks",
    pre: null,
    cat: "general",
    startingFeat: ["Rogue"],
  },
  alertness: {
    featName: "Alertness",
    effect: "+2 bonus on Listen and Spot checks",
    pre: null,
    cat: "general",
    startingFeat: ["Cleric"],
  },
  animalAffinity: {
    featName: "Animal Affinity",
    effect: "+2 bonus on Handle Animal and Ride checks",
    pre: null,
    cat: "general",
    startingFeat: [],
  },
  apLight: {
    featName: "Armor Proficieny (light)",
    effect: "No armor check penalty on attack rolls",
    pre: null,
    cat: "general",
    startingFeat: [],
  },
  apMed: {
    featName: "Armor Proficiency (medium)",
    effect: "No armor check penalty on attack rolls",
    pre: "Armor Proficiency (light)",
    cat: "general",
    startingFeat: [],
  },
  apHeavy: {
    featName: "Armor Proficienty (heavy)",
    effect: "No armor check penalty on attack rolls",
    pre: "Armor Proficiency (medium)",
    cat: "general",
    startingFeat: [],
  },
  athletic: {
    featName: "Athletic",
    effect: "+2 bonus on Climb and Swim checks",
    pre: null,
    cat: "general",
    startingFeat: [],
  },
  augmentSummoning: {
    featName: "Augment Summoning",
    effect: "Summoned creatures gain +4 Str, +4 Con",
    pre: "Spell Focus (conjuration)",
    cat: "general",
    startingFeat: [],
  },
  blindFight: {
    featName: "Blind Fight",
    effect: "Reroll miss chance for concealment",
    pre: null,
    cat: "general",
    startingFeat: ["Monk"],
  },
  combatCasting: {
    featName: "Combat Casting",
    effect: "+4 bonus on Concentration checks for defensive casting",
    pre: null,
    cat: "general",
    startingFeat: ["Sorcerer", "Wizard", "Cleric", "Druid"],
  },
  combatExpertise: {
    featName: "Combat Expertise",
    effect: "Trade attack bonus for AC (max 5 points)",
    pre: "Int 13",
    cat: "general",
    startingFeat: [],
  },
  improvedDisarm: {
    featName: "Improved Disarm",
    effect: "+4 bonus on disarm attempts, no attack of opportunity",
    pre: "Int 13, Combat Expertise",
    cat: "general",
    startingFeat: [],
  },
  improvedFeint: {
    featName: "Improved Feint",
    effect: "Feint in combat as move action",
    pre: "Int 13, Combat Expertise",
    cat: "general",
    startingFeat: [],
  },
  improvedTrip: {
    featName: "Improved Trip",
    effect: "+4 bonus on trip attempts, no attack of opportunity",
    pre: "Int 13, Combat Expertise",
    cat: "general",
    startingFeat: [],
  },
  whirlwindAttack: {
    featName: "Whirlwind Attack",
    effect: "One melee attack against each opponent within reach",
    pre: "Dex 13, Int 13, Combat Expertise, Dodge, Mobility, Spring Attack, base attack bonus +4",
    cat: "general",
    startingFeat: [],
  },
  combatReflexes: {
    featName: "Combat Reflexes",
    effect: "Additional attacks of opportunity",
    pre: null,
    cat: "general",
    startingFeat: ["Fighter"],
  },
  deceitful: {
    featName: "Deceitful",
    effect: "+2 bonus on Disguise and Forgery checks",
    pre: null,
    cat: "general",
    startingFeat: ["Rogue", "Bard"],
  },
  deftHands: {
    featName: "Deft Hands",
    effect: "+2 bonus on Sleight of Hand and Use Rope checks",
    pre: null,
    cat: "general",
    startingFeat: ["Rogue"],
  },
  diligent: {
    featName: "Diligent",
    effect: "+2 bonus on Appraise and Decipher Script checks",
    pre: null,
    cat: "general",
    startingFeat: ["Rogue"],
  },
  dodge: {
    featName: "Dodge",
    effect: "+1 dodge bonus to AC against selected target",
    pre: "Dex 13",
    cat: "general",
    startingFeat: ["Bard", "Monk"],
  },
  mobility: {
    featName: "Mobility",
    effect: "+4 dodge bonus to AC against some attacks of opportunity",
    pre: "Dex 13, Dodge",
    cat: "general",
    startingFeat: ["Monk"],
  },
  springAttack: {
    featName: "Spring Attack",
    effect: "Move before and after melee attack",
    pre: "Dex 13, Dodge, base attack bonus +4",
    cat: "general",
    startingFeat: [],
  },
  endurance: {
    featName: "Endurance",
    effect: "+4 bonus on checks or saves to resist nonlethal damage",
    pre: null,
    cat: "general",
    startingFeat: ["Fighter", "Barbarian", "Ranger", "Paladin"],
  },
  enduranceDiehard: {
    featName: "Endurance - Diehard",
    effect: "Remain conscious at -1 to -9 hitpoints",
    pre: "Endurance",
    cat: "general",
    startingFeat: [],
  },
  eschewMaterials: {
    featName: "Eschew Materials",
    effect: "Cast spells without material components",
    pre: null,
    cat: "general",
    startingFeat: ["Wizard", "Sorcerer"],
  },
  exoticWeaponProficiency: {
    featName: "Exotic Weapon Proficiency",
    effect: "No penalty on attack with specific exotic weapon",
    pre: "Base attack bonus +1",
    cat: "general",
    startingFeat: [],
  },
  extraTurning: {
    featName: "Extra Turning",
    effect: "Can turn or rebuke four more times per day",
    pre: "Ability to turn or rebuke creatures",
    cat: "general",
    startingFeat: [],
  },
  greatFortitude: {
    featName: "Great Fortitude",
    effect: "+2 bonus on Fortitude saves",
    pre: null,
    cat: "general",
    startingFeat: ["Fighter", "Ranger", "Barbarian", "Paladin"],
  },
  improvedCounterspell: {
    featName: "Improved Counterspell",
    effect: "Counterspell with spell of same school",
    pre: null,
    cat: "general",
    startingFeat: [],
  },
  improvedCritical: {
    featName: "Improved Critical",
    effect: "Double threat range of weapon",
    pre: "Proficiency with weapon, base attack bonus +8",
    cat: "general",
    startingFeat: [],
  },
  improvedInitiative: {
    featName: "Improved Initiative",
    effect: "+4 bonus on initiative checks",
    pre: null,
    cat: "general",
    startingFeat: ["Fighter", "Paladin", "Rogue"],
  },
  improvedTurning: {
    featName: "Improved Turning",
    effect: "+1 level for turning checks",
    pre: "Ability to turn or rebuke creatures",
    cat: "general",
    startingFeat: [],
  },
  improvedUnarmedStrike: {
    featName: "Improved Unarmed Strike",
    effect: "Considered armed even when unarmed",
    pre: null,
    cat: "general",
    startingFeat: ["Monk"],
  },
  improvedGrapple: {
    featName: "Improved Grapple",
    effect: "+4 bonus on grapple checks, no attack of opportunity",
    pre: "Dex 13, Improved Unarmed Strike",
    cat: "general",
    startingFeat: [],
  },
  deflectArrows: {
    featName: "Deflect Arrows",
    effect: "Deflect one ranged attack per round",
    pre: "Dex 13, Improved Unarmed Strike",
    cat: "general",
    startingFeat: [],
  },
  snatchArrows: {
    featName: "Snatch Arrows",
    effect: "Catch a deflected ranged attack",
    pre: "Dex 13, Deflect Arrows, Improved Unarmed Strike",
    cat: "general",
    startingFeat: [],
  },
  stunningFist: {
    featName: "Stunning Fist",
    effect: "Stun opponent with unarmed strike",
    pre: "Dex 13, Wis 13, Improved Unarmed Strike, base attack bonus +8",
    cat: "general",
    startingFeat: [],
  },
  investigator: {
    featName: "Investigator",
    effect: "+2 bonus on Gather Information and Search checks",
    pre: null,
    cat: "general",
    startingFeat: ["Rogue", "Ranger", "Druid"],
  },
  ironWill: {
    featName: "Iron Will",
    effect: "+2 bonus on Will saves",
    pre: null,
    cat: "general",
    startingFeat: ["Wizard", "Sorcerer"],
  },
  leadership: {
    featName: "Leadership",
    effect: "Attract cohort and followers",
    pre: "Character level 6th",
    cat: "general",
    startingFeat: [],
  },
  lightningReflexes: {
    featName: "Lightning Reflexes",
    effect: "+2 bonus on Reflex saves",
    pre: null,
    cat: "general",
    startingFeat: ["Rogue", "Bard", "Monk", "Ranger"],
  },
  magicalAptitude: {
    featName: "Magical Aptitude",
    effect: "+2 bonus on Spellcraft and Use Magic Device checks",
    pre: null,
    cat: "general",
    startingFeat: [],
  },
  martialWeaponProficiency: {
    featName: "Martial Weapon Proficiency",
    effect: "No penalty on attacks with specific martial weapon",
    pre: null,
    cat: "general",
    startingFeat: [],
  },
  mountedCombat: {
    featName: "Mounted Combat",
    effect: "Negate hits on mount with Ride check",
    pre: "Ride 1 rank",
    cat: "general",
    startingFeat: [],
  },
  mountedArchery: {
    featName: "Mounted Archery",
    effect: "Half penalty for ranged attacks while mounted",
    pre: "Ride 1 rank, Mounted Combat",
    cat: "general",
    startingFeat: [],
  },
  rideByAttack: {
    featName: "Ride-By Attack",
    effect: "Move before and after a mounted charge",
    pre: "Ride 1 rank, mounted combat",
    cat: "general",
    startingFeat: [],
  },
  spiritedCharge: {
    featName: "Spirited Charge",
    effect: "Double damage with mounted charge",
    pre: "Ride 1 rank, Mounted Combat, Ride-By Attack",
    cat: "general",
    startingFeat: [],
  },
  trample: {
    featName: "Trample",
    effect: "Target cannot avoid mounted overrun",
    pre: "Ride 1 rank, Mounted Combat",
    cat: "general",
    startingFeat: [],
  },
  naturalSpell: {
    featName: "Natural Spell",
    effect: "Cast spells while in wild shape",
    pre: "Wis 13, Ability to use wild shape",
    cat: "general",
    startingFeat: [],
  },
  negotiator: {
    featName: "Negotiator",
    effect: "+2 bonus on Diplomacy and Sense Motive checks",
    pre: null,
    cat: "general",
    startingFeat: ["Bard", "Paladin", "Cleric"],
  },
  nimbleFingers: {
    featName: "Nimble Fingers",
    effect: "+2 bonus on Disable Device and Open Lock checks",
    pre: null,
    cat: "general",
    startingFeat: ["Rogue", "Bard"],
  },
  persuasive: {
    featName: "Persuasive",
    effect: "+2 bonus on Bluff and Intimidate checks",
    pre: null,
    cat: "general",
    startingFeat: ["Barbarian", "Rogue", "Bard"],
  },
  pointBlankShot: {
    featName: "Point Blank Shot",
    effect: "+1 bonus on ranged attack and damage within 30 ft.",
    pre: null,
    cat: "general",
    startingFeat: ["Ranger"],
  },
  farShot: {
    featName: "Far Shot",
    effect: "Increase range increment by 50% or 100%",
    pre: "Point Blank Shot",
    cat: "general",
    startingFeat: [],
  },
  preciseShot: {
    featName: "Precise Shot",
    effect: "No -4 penalty for shooting into melee",
    pre: "Point Blank Shot",
    cat: "general",
    startingFeat: [],
  },
  improvedPreciseShot: {
    featName: "Improved Precise Shot",
    effect: "Ignore less than total cover/concealment for ranged attacks",
    pre: "Dex 19, Point Blank Shot, Precise Shot, base attack bonus +11",
    cat: "general",
    startingFeat: [],
  },
  rapidShot: {
    featName: "Rapid Shot",
    effect: "One extra ranged attack each round",
    pre: "Dex 13, Point Blank Shot",
    cat: "general",
    startingFeat: [],
  },
  manyShot: {
    featName: "Manyshot",
    effect: "Shoot two or more arrows simultaneously",
    pre: "Dex 17, Point Blank Shot, Rapid Shot, base attack bonus +6",
    cat: "general",
    startingFeat: [],
  },
  shotOnTheRun: {
    featName: "Shot on the Run",
    effect: "Move before and after ranged attack",
    pre: "Dex 13, Dodge, Mobility, Point Blank Shot, base attack bonus +4",
    cat: "general",
    startingFeat: [],
  },
  powerAttack: {
    featName: "Power Attack",
    effect: "Trade attack bonus for damage (up to base attack bonus)",
    pre: "Str 13",
    cat: "general",
    startingFeat: ["Fighter"],
  },
  cleave: {
    featName: "Cleave",
    effect: "Extra melee attack after dropping target",
    pre: "Str 13, Power Attack",
    cat: "general",
    startingFeat: [],
  },
  greatCleave: {
    featName: "Great Cleave",
    effect: "No limit to cleave attacks each round",
    pre: "Str 13, Cleave, Power Attack, base attack bonus +4",
    cat: "general",
    startingFeat: [],
  },
  improvedBullRush: {
    featName: "Improved Bull Rush",
    effect: "+4 on bull rush attempts, no attack of opportunity",
    pre: "Str 13, Power Attack",
    cat: "general",
    startingFeat: [],
  },
  improvedOverrun: {
    featName: "Improved Overrun",
    effect: "+4 bonus on overrun attempts, no attack of opportunity",
    pre: "Str 13, Power Attack",
    cat: "general",
    startingFeat: [],
  },
  improvedSunder: {
    featName: "Improved Sunder",
    effect: "+4 bonus on sunder attempts, no attack of opportunity",
    pre: "Str 13, Power Attack",
    cat: "general",
    startingFeat: [],
  },
  quickDraw: {
    featName: "Quick Draw",
    effect: "Draw weapon as free action",
    pre: "Base attack bonus +1",
    cat: "general",
    startingFeat: [],
  },
  rapidReload: {
    featName: "Rapid Reload",
    effect: "Reload crossbow more quickly",
    pre: "Weapon Proficiency with crossbow",
    cat: "general",
    startingFeat: [],
  },
  run: {
    featName: "Run",
    effect:
      "Run at 5 times normal speed, +4 bonus on Jump checks made after running start",
    pre: null,
    cat: "general",
    startingFeat: ["Ranger", "Monk", "Druid", "Bard", "Barbarian"],
  },
  selfSufficient: {
    featName: "Self-Sufficient",
    effect: "+2 bonus on Heal and Survival checks",
    pre: null,
    cat: "general",
    startingFeat: ["Cleric", "Druid", "Wizard", "Sorcerer"],
  },
  shieldProficiency: {
    featName: "Shield Proficiency",
    effect: "No armor check penalty on attack rolls",
    pre: null,
    cat: "general",
    startingFeat: ["Paladin"],
  },
  improvedShieldBash: {
    featName: "Improved Shield Bash",
    effect: "Retain shield bonus to AC when shield bashing",
    pre: "Shield Proficiency",
    cat: "general",
    startingFeat: [],
  },
  towerShieldProficiency: {
    featName: "Tower Shield Proficiency",
    effect: "No armor check penalty on attack rolls",
    pre: "Shield Proficiency",
    cat: "general",
    startingFeat: [],
  },
  simpleWeaponProficiency: {
    featName: "Simple Weapon Proficiency",
    effect: "No -4 penalty on attack rolls with simple weapons",
    pre: null,
    cat: "general",
    startingFeat: [],
  },
  skillFocus: {
    featName: "Skill Focus",
    effect: "+3 bonus on checks with selected skill",
    pre: null,
    cat: "general",
    startingFeat: [],
  },
  spellFocus: {
    featName: "Spell Focus",
    effect: "+1 bonus on save DCs against specific school of magic",
    pre: null,
    cat: "general",
    startingFeat: [],
  },
  greaterSpellFocus: {
    featName: "Greater Spell Focus",
    effect: "+1 bonus on save DCs against specific school of magic",
    pre: "Spell Focus",
    cat: "general",
    startingFeat: [],
  },
  spellMastery: {
    featName: "Spell Mastery",
    effect: "Can prepare some spells without spellbook",
    pre: "Wizard level 1st",
    cat: "general",
    startingFeat: [],
  },
  spellPenetration: {
    featName: "Spell Penetration",
    effect: "+2 bonus on caster level checks to defeat spell resistance",
    pre: null,
    cat: "general",
    startingFeat: [],
  },
  greaterSpellPenetration: {
    featName: "Greater Spell Penetration",
    effect: "+2 bonus on caster level checks to defat spell resistance",
    pre: "Spell Penetration",
    cat: "general",
    startingFeat: [],
  },
  stealthy: {
    featName: "Stealthy",
    effect: "+2 bonus on Hide and Move Silently checks",
    pre: null,
    cat: "general",
    startingFeat: ["Rogue"],
  },
  toughness: {
    featName: "Toughness",
    effect: "+3 hit points",
    pre: null,
    cat: "general",
    startingFeat: ["Sorcerer", "Wizard"],
  },
  track: {
    featName: "Track",
    effect: "Use Survival skill to track",
    pre: null,
    cat: "general",
    startingFeat: [],
  },
  twoWeaponFighting: {
    featName: "Two-Weapon Fighting",
    effect: "Reduce two-weapon fighting penalties",
    pre: "Dex 15",
    cat: "general",
    startingFeat: [],
  },
  twoWeaponDefense: {
    featName: "Two-Weapon Defense",
    effect: "Off-hand weapon grants +1 shield bonus to AC",
    pre: "Dex 15, Two-Weapon Fighting",
    cat: "general",
    startingFeat: [],
  },
  improvedTwoWeaponFighting: {
    featName: "Improved Two-Weapon Fighting",
    effect: "Gain second off-hand attack",
    pre: "Dex 17, Two-Weapon Fighting, base attack bonus +6",
    cat: "general",
    startingFeat: [],
  },
  greaterTwoWeaponFighting: {
    featName: "Greater Two-Weapon Fighting",
    effect: "Gain third off-hand attack",
    pre: "Dex 19, Improved Two-Weapon Fighting, Two-Weapon Fighting, base attack bonus +11",
    cat: "general",
    startingFeat: [],
  },
  weaponFinesse: {
    featName: "Weapon Finesse",
    effect:
      "Use Dex modifier instead of Str modifier on attack rolls with light melee weapons",
    pre: "Base attack bonus +1",
    cat: "general",
    startingFeat: [],
  },
  weaponFocus: {
    featName: "Weapon Focus",
    effect: "+1 bonus on attack rolls with selected weapon",
    pre: "Proficiency with weaponm, base attack bonus +1",
    cat: "general",
    startingFeat: ["Barbarian", "Fighter", "Paladin"],
  },
  weaponSpecialization: {
    featName: "Weapon Specialization",
    effect: "+2 bonus on damage rolls with selected weapon",
    pre: "Proficiency with weapon, Weapon Focus with weapon, fighter level 4th",
    cat: "general",
    startingFeat: [],
  },
  greaterWeaponFocus: {
    featName: "Greater Weapon Focus",
    effect: "+1 bonus on attack rolls with selected weapon",
    pre: "Proficiency with weapon, Weapon Focus with weaponm fighter level 8th",
    cat: "general",
    startingFeat: [],
  },
  greaterWeaponSpecialization: {
    featName: "Greater Weapon Specialization",
    effect: "+2 bonus on damage rolls with selected weapon",
    pre: "Proficiency with weapon, Greater Weapon Focus with weapon, Weapon Focus with weapon, Weapon Specialization with weapon, fighter level 12th",
    cat: "general",
    startingFeat: [],
  },
  brewPotion: {
    featName: "Brew Potion",
    effect: "Create magic potions",
    pre: "Caster level 3rd",
    cat: "item",
    startingFeat: [],
  },
  craftMagicArmsAndArmor: {
    featName: "Craft Magic Arms and Armor",
    effect: "Create magic weapons, armor and shields",
    pre: "Caster level 5th",
    cat: "item",
    startingFeat: [],
  },
  craftRod: {
    featName: "Craft Rod",
    effect: "Create magic rods",
    pre: "Caster level 9th",
    cat: "item",
    startingFeat: [],
  },
  craftStaff: {
    featName: "Craft Staff",
    effect: "Create magic staffs",
    pre: "Caster level 12th",
    cat: "item",
    startingFeat: [],
  },
  craftWand: {
    featName: "Craft Wand",
    effect: "Create magic wands",
    pre: "Caster level 5th",
    cat: "item",
    startingFeat: [],
  },
  craftWondrousItem: {
    featName: "Craft Wondrous Item",
    effect: "Create magic wondrous items",
    pre: "Caster level 3rd",
    cat: "item",
    startingFeat: [],
  },
  forgeRing: {
    featName: "Forge Ring",
    effect: "Create magic rings",
    pre: "Caster level 12th",
    cat: "item",
    startingFeat: [],
  },
  scribeScroll: {
    featName: "Scribe Scroll",
    effect: "Create magic scrolls",
    pre: "Caster level 1st",
    cat: "item",
    startingFeat: ["Cleric", "Druid"],
  },
  empowerSpell: {
    featName: "Empower Spell",
    effect: "Increase spell's variable, numeric effects by 50%",
    pre: null,
    cat: "metamagic",
    startingFeat: [],
  },
  enlargeSpell: {
    featName: "Enlarge Spell",
    effect: "Double spell's range",
    pre: null,
    cat: "metamagic",
    startingFeat: [],
  },
  extendSpell: {
    featName: "Extend Spell",
    effect: "Double spell's duration",
    pre: null,
    cat: "metamagic",
    startingFeat: [],
  },
  heightenSpell: {
    featName: "Heighten Spell",
    effect: "Cast spells as higher level",
    pre: null,
    cat: "metamagic",
    startingFeat: [],
  },
  maximizeSpell: {
    featName: "Maximize Spell",
    effect: "Maximize spell's variable, number effects",
    pre: null,
    cat: "metamagic",
    startingFeat: [],
  },
  quickenSpell: {
    featName: "Quicken Spell",
    effect: "Cast spells as free action",
    pre: null,
    cat: "metamagic",
    startingFeat: [],
  },
  silentSpell: {
    featName: "Silent Spell",
    effect: "Cast spells without verbal components",
    pre: null,
    cat: "metamagic",
    startingFeat: [],
  },
  stillSpell: {
    featName: "Still Spell",
    effect: "Cast spells without somatic component",
    pre: null,
    cat: "metamagic",
    startingFeat: [],
  },
  widenSpell: {
    featName: "Widen Spell",
    effect: "Double spell's area",
    pre: null,
    cat: "metamagic",
    startingFeat: [],
  },
};
