export const skillTables = {
appraise: {
    skillName: "Appraise",
    ability: "Int",
    untrained: true,
    Barbarian: false,
    Bard: true,
    Cleric: false,
    Druid: false,
    Fighter: false,
    Monk: false,
    Paladain: false,
    Ranger: false,
    Rogue: true,
    Sorcerer: false,
    Wizard: false,
},
balance: {
    skillName: "Balance",
    ability: "Dex",
    untrained: true,
    Barbarian: false,
    Bard: true,
    Cleric: false,
    Druid: false,
    Fighter: false,
    Monk: true,
    Paladain: false,
    Ranger: false,
    Rogue: true,
    Sorcerer: false,
    Wizard: false,
},
bluff: {
    skillName: "Bluff",
    ability: "Cha",
    untrained: true,
    Barbarian: false,
    Bard: true,
    Cleric: false,
    Druid: false,
    Fighter: false,
    Monk: false,
    Paladain: false,
    Ranger: false,
    Rogue: true,
    Sorcerer: true,
    Wizard: false,
},
climb: {
    skillName: "Climb",
    ability: "Str",
    untrained: true,
    Barbarian: true,
    Bard: true,
    Cleric: false,
    Druid: false,
    Fighter: true,
    Monk: true,
    Paladain: false,
    Ranger: true,
    Rogue: true,
    Sorcerer: false,
    Wizard: false,
},
concentraion: {
    skillName: "Concentration",
    ability: "Con",
    untrained: true,
    Barbarian: false,
    Bard: true,
    Cleric: true,
    Druid: true,
    Fighter: false,
    Monk: true,
    Paladain: true,
    Ranger: true,
    Rogue: false,
    Sorcerer: true,
    Wizard: true,
}

}
