export const skillTables = {
  appraise: {
    skillName: "Appraise",
    ability: "Int",
    untrained: true,
    Barbarian: false,
    Bard: true,
    Cleric: false,
    Druid: false,
    Fighter: false,
    Monk: false,
    Paladin: false,
    Ranger: false,
    Rogue: true,
    Sorcerer: false,
    Wizard: false,
    startingSkill: [],
  },
  balance: {
    skillName: "Balance",
    ability: "Dex",
    untrained: true,
    Barbarian: false,
    Bard: true,
    Cleric: false,
    Druid: false,
    Fighter: false,
    Monk: true,
    Paladin: false,
    Ranger: false,
    Rogue: true,
    Sorcerer: false,
    Wizard: false,
    startingSkill: [],
  },
  bluff: {
    skillName: "Bluff",
    ability: "Cha",
    untrained: true,
    Barbarian: false,
    Bard: true,
    Cleric: false,
    Druid: false,
    Fighter: false,
    Monk: false,
    Paladin: false,
    Ranger: false,
    Rogue: true,
    Sorcerer: true,
    Wizard: false,
    startingSkill: [],
  },
  climb: {
    skillName: "Climb",
    ability: "Str",
    untrained: true,
    Barbarian: true,
    Bard: true,
    Cleric: false,
    Druid: false,
    Fighter: true,
    Monk: true,
    Paladin: false,
    Ranger: true,
    Rogue: true,
    Sorcerer: false,
    Wizard: false,
    startingSkill: ["Barbarian"],
  },
  concentraion: {
    skillName: "Concentration",
    ability: "Con",
    untrained: true,
    Barbarian: false,
    Bard: true,
    Cleric: true,
    Druid: true,
    Fighter: false,
    Monk: true,
    Paladin: true,
    Ranger: true,
    Rogue: false,
    Sorcerer: true,
    Wizard: true,
    startingSkill: [],
  },
  craft: {
    skillName: "Craft",
    ability: "Int",
    untrained: true,
    Barbarian: true,
    Bard: true,
    Cleric: true,
    Druid: true,
    Fighter: true,
    Monk: true,
    Paladin: true,
    Ranger: true,
    Rogue: true,
    Sorcerer: true,
    Wizard: true,
    startingSkill: [],
  },
  decipher: {
    skillName: "Decipher Script",
    ability: "Int",
    untrained: false,
    Barbarian: false,
    Bard: true,
    Cleric: false,
    Druid: false,
    Fighter: false,
    Monk: false,
    Paladin: false,
    Ranger: false,
    Rogue: true,
    Sorcerer: false,
    Wizard: true,
    startingSkill: [],
  },
  diplomacy: {
    skillName: "Diplomacy",
    ability: "Cha",
    untrained: true,
    Barbarian: false,
    Bard: true,
    Cleric: true,
    Druid: true,
    Fighter: false,
    Monk: true,
    Paladin: true,
    Ranger: false,
    Rogue: true,
    Sorcerer: false,
    Wizard: false,
    startingSkill: [],
  },
  disable: {
    skillName: "Disable Device",
    ability: "Int",
    untrained: false,
    Barbarian: false,
    Bard: false,
    Cleric: false,
    Druid: false,
    Fighter: false,
    Monk: false,
    Paladin: false,
    Ranger: false,
    Rogue: true,
    Sorcerer: false,
    Wizard: false,
    startingSkill: [],
  },
  disguise: {
    skillName: "Disguise",
    ability: "Cha",
    untrained: true,
    Barbarian: false,
    Bard: true,
    Cleric: false,
    Druid: false,
    Fighter: false,
    Monk: false,
    Paladin: false,
    Ranger: false,
    Rogue: true,
    Sorcerer: false,
    Wizard: false,
    startingSkill: [],
  },
  escapeArtist: {
    skillName: "Escape Artist",
    ability: "Dex",
    untrained: true,
    Barbarian: false,
    Bard: true,
    Cleric: false,
    Druid: false,
    Fighter: false,
    Monk: true,
    Paladin: false,
    Ranger: false,
    Rogue: true,
    Sorcerer: false,
    Wizard: false,
    startingSkill: [],
  },
  forgery: {
    skillName: "Forgery",
    ability: "Int",
    untrained: true,
    Barbarian: false,
    Bard: false,
    Cleric: false,
    Druid: false,
    Fighter: false,
    Monk: false,
    Paladin: false,
    Ranger: false,
    Rogue: true,
    Sorcerer: false,
    Wizard: false,
    startingSkill: [],
  },
  gatherInformation: {
    skillName: "Gather Information",
    ability: "Cha",
    untrained: true,
    Barbarian: false,
    Bard: true,
    Cleric: false,
    Druid: false,
    Fighter: false,
    Monk: false,
    Paladin: false,
    Ranger: false,
    Rogue: true,
    Sorcerer: false,
    Wizard: false,
    startingSkill: [],
  },
  handleAnimal: {
    skillName: "Handle Animal",
    ability: "Cha",
    untrained: false,
    Barbarian: true,
    Bard: false,
    Cleric: false,
    Druid: true,
    Fighter: true,
    Monk: false,
    Paladin: true,
    Ranger: true,
    Rogue: false,
    Sorcerer: false,
    Wizard: false,
    startingSkill: [],
  },
  heal: {
    skillName: "Heal",
    ability: "Wis",
    untrained: true,
    Barbarian: false,
    Bard: false,
    Cleric: true,
    Druid: true,
    Fighter: false,
    Monk: false,
    Paladin: true,
    Ranger: true,
    Rogue: false,
    Sorcerer: false,
    Wizard: false,
    startingSkill: [],
  },
  hide: {
    skillName: "Hide",
    ability: "Dex",
    untrained: true,
    Barbarian: false,
    Bard: true,
    Cleric: false,
    Druid: false,
    Fighter: false,
    Monk: true,
    Paladin: false,
    Ranger: true,
    Rogue: true,
    Sorcerer: false,
    Wizard: false,
    startingSkill: [],
  },
  intimidate: {
    skillName: "Intimidate",
    ability: "Cha",
    untrained: true,
    Barbarian: true,
    Bard: false,
    Cleric: false,
    Druid: false,
    Fighter: true,
    Monk: false,
    Paladin: false,
    Ranger: false,
    Rogue: true,
    Sorcerer: false,
    Wizard: false,
    startingSkill: [],
  },
  jump: {
    skillName: "Jump",
    ability: "Str",
    untrained: true,
    Barbarian: true,
    Bard: true,
    Cleric: false,
    Druid: false,
    Fighter: true,
    Monk: true,
    Paladin: false,
    Ranger: true,
    Rogue: true,
    Sorcerer: false,
    Wizard: false,
    startingSkill: ["Barbarian"],
  },
  knowledgeArcana: {
    skillName: "Knowledge (arcana)",
    ability: "Int",
    untrained: false,
    Barbarian: false,
    Bard: true,
    Cleric: true,
    Druid: false,
    Fighter: false,
    Monk: true,
    Paladin: false,
    Ranger: false,
    Rogue: false,
    Sorcerer: true,
    Wizard: true,
    startingSkill: [],
  },
  knowledgeArchitect: {
    skillName: "Knowledge (architecture and engineering)",
    ability: "Int",
    untrained: false,
    Barbarian: false,
    Bard: true,
    Cleric: false,
    Druid: false,
    Fighter: false,
    Monk: false,
    Paladin: false,
    Ranger: false,
    Rogue: false,
    Sorcerer: false,
    Wizard: true,
    startingSkill: [],
  },

  knowledgeDungeon: {
    skillName: "Knowledge (dungeoneering)",
    ability: "Int",
    untrained: false,
    Barbarian: false,
    Bard: true,
    Cleric: false,
    Druid: false,
    Fighter: false,
    Monk: false,
    Paladin: false,
    Ranger: true,
    Rogue: false,
    Sorcerer: false,
    Wizard: true,
    startingSkill: [],
  },

  knowledgeGeography: {
    skillName: "Knowledge (geography)",
    ability: "Int",
    untrained: false,
    Barbarian: false,
    Bard: true,
    Cleric: false,
    Druid: false,
    Fighter: false,
    Monk: false,
    Paladin: false,
    Ranger: true,
    Rogue: false,
    Sorcerer: false,
    Wizard: true,
    startingSkill: [],
  },

  knowledgeHistory: {
    skillName: "Knowledge (history)",
    ability: "Int",
    untrained: false,
    Barbarian: false,
    Bard: true,
    Cleric: true,
    Druid: false,
    Fighter: false,
    Monk: false,
    Paladin: false,
    Ranger: false,
    Rogue: false,
    Sorcerer: false,
    Wizard: true,
    startingSkill: [],
  },

  knowledgelocal: {
    skillName: "Knowledge (local)",
    ability: "Int",
    untrained: false,
    Barbarian: false,
    Bard: true,
    Cleric: false,
    Druid: false,
    Fighter: false,
    Monk: false,
    Paladin: false,
    Ranger: true,
    Rogue: false,
    Sorcerer: false,
    Wizard: true,
    startingSkill: [],
  },

  knowledgeNature: {
    skillName: "Knowledge (nature)",
    ability: "Int",
    untrained: false,
    Barbarian: false,
    Bard: true,
    Cleric: false,
    Druid: true,
    Fighter: false,
    Monk: false,
    Paladin: false,
    Ranger: true,
    Rogue: false,
    Sorcerer: false,
    Wizard: true,
    startingSkill: [],
  },

  knowledgeNobility: {
    skillName: "Knowledge (nobility and royalty)",
    ability: "Int",
    untrained: false,
    Barbarian: false,
    Bard: true,
    Cleric: false,
    Druid: false,
    Fighter: false,
    Monk: false,
    Paladin: true,
    Ranger: false,
    Rogue: false,
    Sorcerer: false,
    Wizard: true,
    startingSkill: [],
  },

  knowledgeReligion: {
    skillName: "Knowledge (religion)",
    ability: "Int",
    untrained: false,
    Barbarian: false,
    Bard: true,
    Cleric: true,
    Druid: false,
    Fighter: false,
    Monk: true,
    Paladin: true,
    Ranger: false,
    Rogue: false,
    Sorcerer: false,
    Wizard: true,
    startingSkill: [],
  },

  knowledgePlanes: {
    skillName: "Knowledge (the planes)",
    ability: "Int",
    untrained: false,
    Barbarian: false,
    Bard: true,
    Cleric: true,
    Druid: false,
    Fighter: false,
    Monk: false,
    Paladin: false,
    Ranger: false,
    Rogue: false,
    Sorcerer: false,
    Wizard: true,
    startingSkill: [],
  },

  listen: {
    skillName: "Listen",
    ability: "Wis",
    untrained: true,
    Barbarian: true,
    Bard: true,
    Cleric: false,
    Druid: true,
    Fighter: false,
    Monk: true,
    Paladin: false,
    Ranger: true,
    Rogue: true,
    Sorcerer: false,
    Wizard: false,
    startingSkill: ["Barbarian"],
  },

  moveSilently: {
    skillName: "Move Silently",
    ability: "Dex",
    untrained: true,
    Barbarian: false,
    Bard: true,
    Cleric: false,
    Druid: false,
    Fighter: false,
    Monk: true,
    Paladin: false,
    Ranger: true,
    Rogue: true,
    Sorcerer: false,
    Wizard: false,
    startingSkill: [],
  },

  openLock: {
    skillName: "Open Lock",
    ability: "Dex",
    untrained: false,
    Barbarian: false,
    Bard: false,
    Cleric: false,
    Druid: false,
    Fighter: false,
    Monk: false,
    Paladin: false,
    Ranger: false,
    Rogue: true,
    Sorcerer: false,
    Wizard: false,
    startingSkill: [],
  },

  perform: {
    skillName: "Perform",
    ability: "Dex",
    untrained: true,
    Barbarian: false,
    Bard: true,
    Cleric: false,
    Druid: false,
    Fighter: false,
    Monk: true,
    Paladin: false,
    Ranger: false,
    Rogue: true,
    Sorcerer: false,
    Wizard: false,
    startingSkill: [],
  },

  profession: {
    skillName: "Profession",
    ability: "Wis",
    untrained: false,
    Barbarian: false,
    Bard: true,
    Cleric: true,
    Druid: true,
    Fighter: false,
    Monk: true,
    Paladin: true,
    Ranger: true,
    Rogue: true,
    Sorcerer: true,
    Wizard: true,
    startingSkill: [],
  },

  ride: {
    skillName: "Ride",
    ability: "Dex",
    untrained: true,
    Barbarian: true,
    Bard: false,
    Cleric: false,
    Druid: true,
    Fighter: true,
    Monk: false,
    Paladin: true,
    Ranger: true,
    Rogue: false,
    Sorcerer: false,
    Wizard: false,
    startingSkill: [],
  },

  search: {
    skillName: "Search",
    ability: "Int",
    untrained: true,
    Barbarian: false,
    Bard: false,
    Cleric: false,
    Druid: false,
    Fighter: false,
    Monk: false,
    Paladin: false,
    Ranger: true,
    Rogue: true,
    Sorcerer: false,
    Wizard: false,
    startingSkill: [],
  },

  senseMotive: {
    skillName: "Sense Motive",
    ability: "Int",
    untrained: true,
    Barbarian: false,
    Bard: true,
    Cleric: false,
    Druid: false,
    Fighter: false,
    Monk: true,
    Paladin: true,
    Ranger: false,
    Rogue: true,
    Sorcerer: false,
    Wizard: false,
    startingSkill: [],
  },

  sleightHand: {
    skillName: "Sleight of Hand",
    ability: "Dex",
    untrained: false,
    Barbarian: false,
    Bard: true,
    Cleric: false,
    Druid: false,
    Fighter: false,
    Monk: false,
    Paladin: false,
    Ranger: false,
    Rogue: true,
    Sorcerer: false,
    Wizard: false,
    startingSkill: [],
  },

  speakLanguage: {
    skillName: "Speak Language",
    ability: null,
    untrained: false,
    Barbarian: false,
    Bard: true,
    Cleric: false,
    Druid: false,
    Fighter: false,
    Monk: false,
    Paladin: false,
    Ranger: false,
    Rogue: false,
    Sorcerer: false,
    Wizard: false,
    startingSkill: [],
  },

  spellcraft: {
    skillName: "Spellcraft",
    ability: "Int",
    untrained: false,
    Barbarian: false,
    Bard: true,
    Cleric: true,
    Druid: true,
    Fighter: false,
    Monk: false,
    Paladin: false,
    Ranger: false,
    Rogue: false,
    Sorcerer: true,
    Wizard: true,
    startingSkill: [],
  },

  spot: {
    skillName: "Spot",
    ability: "Wis",
    untrained: true,
    Barbarian: false,
    Bard: false,
    Cleric: false,
    Druid: true,
    Fighter: false,
    Monk: true,
    Paladin: false,
    Ranger: true,
    Rogue: true,
    Sorcerer: false,
    Wizard: false,
    startingSkill: [],
  },

  survival: {
    skillName: "Survival",
    ability: "Wis",
    untrained: true,
    Barbarian: true,
    Bard: false,
    Cleric: false,
    Druid: true,
    Fighter: false,
    Monk: false,
    Paladin: false,
    Ranger: true,
    Rogue: false,
    Sorcerer: false,
    Wizard: false,
    startingSkill: ["Barbarian"],
  },

  swim: {
    skillName: "Swim",
    ability: "Str",
    untrained: true,
    Barbarian: true,
    Bard: true,
    Cleric: false,
    Druid: true,
    Fighter: true,
    Monk: true,
    Paladin: false,
    Ranger: true,
    Rogue: true,
    Sorcerer: false,
    Wizard: false,
    startingSkill: [],
  },

  tumble: {
    skillName: "Tumble",
    ability: "Dex",
    untrained: false,
    Barbarian: false,
    Bard: true,
    Cleric: false,
    Druid: false,
    Fighter: false,
    Monk: true,
    Paladin: false,
    Ranger: false,
    Rogue: true,
    Sorcerer: false,
    Wizard: false,
    startingSkill: [],
  },

  useMagicDevice: {
    skillName: "Use Magic Device",
    ability: "Cha",
    untrained: false,
    Barbarian: false,
    Bard: true,
    Cleric: false,
    Druid: false,
    Fighter: false,
    Monk: false,
    Paladin: false,
    Ranger: false,
    Rogue: true,
    Sorcerer: false,
    Wizard: false,
    startingSkill: [],
  },

  useRope: {
    skillName: "Use Rope",
    ability: "Dex",
    untrained: true,
    Barbarian: false,
    Bard: false,
    Cleric: false,
    Druid: false,
    Fighter: false,
    Monk: false,
    Paladin: false,
    Ranger: true,
    Rogue: true,
    Sorcerer: false,
    Wizard: false,
    startingSkill: [],
  },
};
